services:
  - type: web
    name: kidney-disease-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn medical_classification.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: medical_classification.settings
    staticPublishPath: staticfiles
