services:
  - type: web
    name: kidney-disease-app
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: medical_classification.settings
      - key: PYTHONUNBUFFERED
        value: "1"
