# Generated by Django 4.1 on 2024-07-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("disease_detection", "0002_braintumormodel_p_disease_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="BrainTumorModel",),
        migrations.DeleteModel(name="ChestDiseaseModel",),
        migrations.DeleteModel(name="SkinDiseaseModel",),
    ]
